version: '3.7' 

services: 
  app:
    build: 
      context: . 
      dockerfile: Dockerfile 
    volumes: 
      # Mount the current directory contents underneath /mothership inside the container 
      - ./mothership:/mothership
